s = set()
n = input("Enter No. 1: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
s = set()
n = input("Enter No.: ")
s.add(int(n))
print(s)